/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    @Test
    void diceRollReturnsArraysOfRolls() {
        int testRoll = 5;
    //Set new library
        Library sut = new Library();

        int[] rollResult = new int[5];
        rollResult = sut.roll(testRoll);

        assertTrue(rollResult.length == testRoll);
    }

    @Test
    void duplicatesInArray() {

        int [] duplicateArray = {1 , 3, 2 , 4, 2};

        Library sut = new Library();
       boolean duplicateResult = sut.containsDuplicate(duplicateArray);
         assertTrue(duplicateResult);

    }

    @Test void averageOfArray() {

        double[] result = {3, 5, 9};
        Library sut = new Library();
        double averageResult = sut.calculateAverage(result);
        System.out.println(averageResult);
        assertTrue(averageResult == 5.666666666666667);
    }

    @Test
    void minAverageArray() {
        Library sut = new Library();
        double[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        double[] newArr =   {55, 54, 60, 53, 59, 57, 61};
        double[] result = sut.lowestAverageTemp(weeklyMonthTemperatures);
        assertArrayEquals(result, newArr);
    }

}