/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    @Test
    void diceRollReturnsArraysOfRolls() {
        int testRoll = 5;
    //Set new library
        Library sut = new Library();

        int[] rollResult = new int[5];
        rollResult = sut.roll(testRoll);

        assertTrue(rollResult.length == testRoll);
    }

    @Test
    void duplicatesInArray() {

        int [] duplicateArray = {1 , 3, 2 , 4, 2};

        Library sut = new Library();
       boolean duplicateResult = sut.containsDuplicate(duplicateArray);
         assertTrue(duplicateResult);

    }

    @Test
    void averageOfArray() {
        double [] averageArray = {22};

        Library sut = new Library();

        double averageResult = sut.calculateAverage(averageArray);
        assertEquals(averageResult == averageArray);

    }

}