/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    @Test
    void diceRollReturnsArraysOfRolls() {
        int testRoll = 5;
    //Set new library
        Library sut = new Library();

        int[] rollResult = new int[5];
        rollResult = sut.roll(testRoll);

        assertTrue(rollResult.length == testRoll);
    }

    @Test
    void duplicatesInArray() {

        int [] duplicateArray = {1 , 3, 2 , 4, 2};

        Library sut = new Library();
       boolean duplicateResult = sut.containsDuplicate(duplicateArray);
         assertTrue(duplicateResult);

    }

    @Test void averageOfArray() {

        int[] result = {2, 2, 2};
        Library sut = new Library();
        int averageResult = sut.calculateAverage(result);
        System.out.println(averageResult);
        assertTrue(averageResult == 2);
    }

    @Test
    void minAverageArray() {
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] newArr =   {55, 54, 60, 53, 59, 57, 61};
        int[] result = sut.lowestAverageTemp(weeklyMonthTemperatures);
        assertArrayEquals(result, newArr);
    }

    @Test
    void minMaxTemperatures() {
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String response = "High: 72" + "\n" + "Low: 51" + "\n" + "Never saw temperature: 63" + "\n" + "Never saw temperature: 67" + "\n" + "Never saw temperature: 68" + "\n" + "Never saw temperature: 69";
        String result = sut.minMaxTemp(weeklyMonthTemperatures);
        assertEquals(result, response);
    }

}