/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void dollarSigns() {
        Restaurant setName = new Restaurant("Dim Sum Garden", 5, "$$");
        System.out.println(setName);
    }

    @Test void sendReview() {
        Review setAuthor = new Review(4, "Best Spicy Soup Dumplings in Philly!", "Mr. Foodie");
        System.out.println(setAuthor);
    }

    @Test void makeReview() {
        Restaurant info = new Restaurant("Standard Tap", 5, "$$");
        Review review = new Review(5, "You can't go wrong with anything in the menu!", "Mehtab");
        info.addReview(review);
        assert(review.toString().equals("{You can't go wrong with anything in the menu!, Mehtab}"));
    }
}
